--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ihsan48/SimpleGamemode
build-by-default: true
branches:
- main
projects:
  SimpleGamemode:
    path: ""
    lint:
      phpstan: false
...
