name: EasyGameChange
version: 1.0.0
api: 5.0.0
main: Ihsan48\EasyGameChange\Loader
author: Ihsan48

commands:
  gmc:
    description: "Change gamemode to Creative"
    permission: easygamechange.creative
  gms:
    description: "Change gamemode to Survival"
    permission: easygamechange.survival
  gmspc:
    description: "Change gamemode to Spectator"
    permission: easygamechange.spectator

permissions:
  easygamechange.creative:
    default: op
  easygamechange.creative.other:
    default: op
  easygamechange.survival:
    default: op
  easygamechange.survival.other:
    default: op
  easygamechange.spectator:
    default: op
  easygamechange.spectator.other:
    default: op
